#! /bin/bash

WINNAME=$(xdotool getwindowfocus getwindowname)

# requires specifc tmux title configuration
if [[ $WINNAME =~ emacs.* ]]; then
  # open terminal in dir of emacs buffer
  # depends on corresponding snippet in .emacs
  xdotool key F5
elif [[ $WINNAME =~ tmux.* ]]; then
  # send tmux prefix sequence
  xdotool key ctrl+b
else
  # open new st window
  xdotool key alt+shift+Return
fi
