#! /bin/bash

WINNAME=$(xdotool getwindowfocus getwindowname)

# requires specifc tmux title configuration
if [[ $WINNAME =~ emacs.* ]]; then
  # toggle clockin-clockout
  # depends on corresponding snippet in .emacs
  xdotool key F5
elif [[ $WINNAME =~ tmux.* ]]; then
  # send tmux prefix sequence
  xdotool key ctrl+b
else
  # open new urxvt window
  xdotool key alt+shift+u
fi
